/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/avatar-model.glb -t 
*/

import * as THREE from "three"
import React from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    Hoodie: THREE.Mesh
    Shoe_VansShoeMaterial_0: THREE.Mesh
    Hand_R: THREE.Mesh
    Pants: THREE.Mesh
    Plane020: THREE.Mesh
    Plane020_1: THREE.Mesh
    Plane020_2: THREE.Mesh
    Plane020_3: THREE.Mesh
    Plane020_4: THREE.Mesh
    Boy_Face_Retopo003: THREE.Mesh
    Eye_Lash_L001: THREE.Mesh
    Eye_Lash_R001: THREE.Mesh
    Eyebrow_L: THREE.Mesh
    Eyebrow_R: THREE.Mesh
    Haur: THREE.Mesh
    ankle: THREE.Mesh
    Eye_Highlight: THREE.Mesh
    Eye_Highlight001: THREE.Mesh
    Tiny_Eye_1050: THREE.Mesh
    Tiny_Eye_1050_1: THREE.Mesh
    Tiny_Eye_1002: THREE.Mesh
    Tiny_Eye_1002_1: THREE.Mesh
  }
  materials: {
    Hoodie: THREE.MeshStandardMaterial
    VansShoeMaterial: THREE.MeshStandardMaterial
    ["Material.007"]: THREE.MeshStandardMaterial
    Pants: THREE.MeshStandardMaterial
    ["Basic_Glass.001"]: THREE.MeshPhysicalMaterial
    ["Material.008"]: THREE.MeshStandardMaterial
    ["Material.009"]: THREE.MeshStandardMaterial
    ["Plastic.001"]: THREE.MeshPhysicalMaterial
    ["Material.010"]: THREE.MeshStandardMaterial
    ["Material.007"]: THREE.MeshStandardMaterial
    ["hair plain"]: THREE.MeshStandardMaterial
    ["Eye Highlight.001"]: THREE.MeshStandardMaterial
    ["Tiny Iris 1.3 (Style Amber)"]: THREE.MeshStandardMaterial
    ["Tiny Sclera 1.3 (Style Amber)"]: THREE.MeshPhysicalMaterial
  }
  // animations: GLTFAction[]
}

export function Avatar(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("models/avatar-model.glb") as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Hoodie.geometry}
        material={materials.Hoodie}
        position={[0.005, 0.199, -0.012]}
        rotation={[1.595, -0.05, 0.012]}
      />
      <mesh
        geometry={nodes.Shoe_VansShoeMaterial_0.geometry}
        material={materials.VansShoeMaterial}
        position={[-0.051, -0.492, 0.009]}
        rotation={[0.052, 0, 0]}
      />
      <mesh
        geometry={nodes.Hand_R.geometry}
        material={materials["Material.007"]}
        position={[-0.264, 0.128, 0.024]}
        rotation={[3.05, -0.58, -0.178]}
      />
      <mesh
        geometry={nodes.Pants.geometry}
        material={materials.Pants}
        position={[-0.003, -0.497, -0.027]}
      />
      <group
        position={[0.187, 0.451, 0.098]}
        rotation={[1.473, 0, 0]}
        scale={[0.095, 0.091, 0.091]}
      >
        <mesh
          geometry={nodes.Plane020.geometry}
          material={materials["Basic_Glass.001"]}
        />
        <mesh
          geometry={nodes.Plane020_1.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Plane020_2.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Plane020_3.geometry}
          material={materials["Plastic.001"]}
        />
        <mesh
          geometry={nodes.Plane020_4.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <mesh
        geometry={nodes.Boy_Face_Retopo003.geometry}
        material={materials["Material.007"]}
        position={[0, 0.445, -0.004]}
      />
      <mesh
        geometry={nodes.Eye_Lash_L001.geometry}
        material={materials["hair plain"]}
      />
      <mesh
        geometry={nodes.Eye_Lash_R001.geometry}
        material={materials["hair plain"]}
      />
      <mesh
        geometry={nodes.Eyebrow_L.geometry}
        material={materials["hair plain"]}
      />
      <mesh
        geometry={nodes.Eyebrow_R.geometry}
        material={materials["hair plain"]}
      />
      <mesh geometry={nodes.Haur.geometry} material={materials["hair plain"]} />
      <mesh
        geometry={nodes.ankle.geometry}
        material={materials["Material.007"]}
        position={[-0.051, -0.492, 0.009]}
        rotation={[0.052, 0, 0]}
      />
      <mesh
        name="Eye_Highlight"
        geometry={nodes.Eye_Highlight.geometry}
        material={materials["Eye Highlight.001"]}
        morphTargetDictionary={nodes.Eye_Highlight.morphTargetDictionary}
        morphTargetInfluences={nodes.Eye_Highlight.morphTargetInfluences}
        position={[0.044, 0.473, 0.046]}
        rotation={[1.445, 0, 0]}
      />
      <mesh
        name="Eye_Highlight001"
        geometry={nodes.Eye_Highlight001.geometry}
        material={materials["Eye Highlight.001"]}
        morphTargetDictionary={nodes.Eye_Highlight001.morphTargetDictionary}
        morphTargetInfluences={nodes.Eye_Highlight001.morphTargetInfluences}
        position={[0.131, 0.473, 0.048]}
        rotation={[1.445, 0, 0]}
      />
      <group
        position={[-0.042, 0.473, 0.046]}
        rotation={[-0.126, 0, 0]}
        scale={2.092}
      >
        <mesh
          name="Tiny_Eye_1050"
          geometry={nodes.Tiny_Eye_1050.geometry}
          material={materials["Tiny Iris 1.3 (Style Amber)"]}
          morphTargetDictionary={nodes.Tiny_Eye_1050.morphTargetDictionary}
          morphTargetInfluences={nodes.Tiny_Eye_1050.morphTargetInfluences}
        />
        <mesh
          name="Tiny_Eye_1050_1"
          geometry={nodes.Tiny_Eye_1050_1.geometry}
          material={materials["Tiny Sclera 1.3 (Style Amber)"]}
          morphTargetDictionary={nodes.Tiny_Eye_1050_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Tiny_Eye_1050_1.morphTargetInfluences}
        />
      </group>
      <group
        position={[0.042, 0.473, 0.046]}
        rotation={[-0.126, 0, 0]}
        scale={2.092}
      >
        <mesh
          name="Tiny_Eye_1002"
          geometry={nodes.Tiny_Eye_1002.geometry}
          material={materials["Tiny Iris 1.3 (Style Amber)"]}
          morphTargetDictionary={nodes.Tiny_Eye_1002.morphTargetDictionary}
          morphTargetInfluences={nodes.Tiny_Eye_1002.morphTargetInfluences}
        />
        <mesh
          name="Tiny_Eye_1002_1"
          geometry={nodes.Tiny_Eye_1002_1.geometry}
          material={materials["Tiny Sclera 1.3 (Style Amber)"]}
          morphTargetDictionary={nodes.Tiny_Eye_1002_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Tiny_Eye_1002_1.morphTargetInfluences}
        />
      </group>
    </group>
  )
}

useGLTF.preload("models/avatar-model.glb")
